services:
  postgres:
    image: postgres:latest
    container_name: bologverket-db_dev_profile
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bologverket_dev_db
    ports:
      - "5453:5432"